### ISSUE TITLE
Intent Schema and Sample Utterances

### ISSUE THREAD

**Issue by PostsDesert** [Danondso/GooglePlayEchoMusicService#1]
Hey, do you have the Intent Schema and Sample Utterances that you used for setting up the music service on amazon? I'm trying to set it up and for the life of me cannot figure out how to get the query for "PlaySingleSongIntent" to work. Thanks, Griffith

**Comment by Danondso** [comment]
Yeah dude, I'm away from compy today but I'll attach the file as soon as I
can get around to it

**Comment by Danondso** [comment]
Hey just a heads up I committed my intent schema and utterances into as
intent_schema.txt, just sync your repo and it should show up.

**Comment by PostsDesert** [comment]
Thanks. So your using a custom slot?

**Comment by Danondso** [comment]
Yeah, I would have use AMAZON.LITERAL but that's being deprecated in favor of custom slots. 
When you make the custom slot for this for the example phrases just use a bunch of random words and a couple phrases. You need to give Alexa 'template' words and phrases in order for her to understand different queries.

**Comment by PostsDesert** [comment]
Okay cool, I just made a pull request for using AMAZON.MusicRecording which has worked so far for me. I haven't tried the custom slot method yet so that may work just as good.

**Comment by Danondso** [comment]
I didn't even know AMAZON.MusicRecording was a thing lol, I'll have to check it out.
